USE [XolarDb]
GO
INSERT INTO [dbo].[Traits] ([Description]) VALUES ('Critical Rating')
INSERT INTO [dbo].[Traits] ([Description]) VALUES ('Magazine Size')
INSERT INTO [dbo].[Traits] ([Description]) VALUES ('Damage')
INSERT INTO [dbo].[Traits] ([Description]) VALUES ('Damage to afflicted targets')
INSERT INTO [dbo].[Traits] ([Description]) VALUES ('Causes Affliction damage for 6 seconds')
INSERT INTO [dbo].[Traits] ([Description]) VALUES ('Reload Speed')
INSERT INTO [dbo].[Traits] ([Description]) VALUES ('Critical Damage')
INSERT INTO [dbo].[Traits] ([Description]) VALUES ('Weapon Damage when aiming down sights')
INSERT INTO [dbo].[Traits] ([Description]) VALUES ('Increased Building Health')
INSERT INTO [dbo].[Traits] ([Description]) VALUES ('Life Leech')
INSERT INTO [dbo].[Traits] ([Description]) VALUES ('Durability')

INSERT INTO [dbo].[Traits] ([Description]) VALUES ('Common')
INSERT INTO [dbo].[Traits] ([Description]) VALUES ('Epic')
INSERT INTO [dbo].[Traits] ([Description]) VALUES ('Legendary')
INSERT INTO [dbo].[Traits] ([Description]) VALUES ('Mythic')
INSERT INTO [dbo].[Traits] ([Description]) VALUES ('Rare')

INSERT INTO [dbo].[Materials] ([Description]) VALUES ('Active Powercell')
INSERT INTO [dbo].[Materials] ([Description]) VALUES ('Adhesive Resin')
INSERT INTO [dbo].[Materials] ([Description]) VALUES ('Bacon')
INSERT INTO [dbo].[Materials] ([Description]) VALUES ('Batteries')
INSERT INTO [dbo].[Materials] ([Description]) VALUES ('Blast Powder')
INSERT INTO [dbo].[Materials] ([Description]) VALUES ('Coal')
INSERT INTO [dbo].[Materials] ([Description]) VALUES ('Shadowshard Crystal')
INSERT INTO [dbo].[Materials] ([Description]) VALUES ('Sunbeam Crystal')
INSERT INTO [dbo].[Materials] ([Description]) VALUES ('Duct Tape')
INSERT INTO [dbo].[Materials] ([Description]) VALUES ('Flower Petals')
INSERT INTO [dbo].[Materials] ([Description]) VALUES ('Fibrous Herbs')
INSERT INTO [dbo].[Materials] ([Description]) VALUES ('Honey')
INSERT INTO [dbo].[Materials] ([Description]) VALUES ('Rusty Mechanical Parts')
INSERT INTO [dbo].[Materials] ([Description]) VALUES ('Simple Mechanical Parts')
INSERT INTO [dbo].[Materials] ([Description]) VALUES ('Sturdy Mechanical Parts')
INSERT INTO [dbo].[Materials] ([Description]) VALUES ('Sleek Mechanical Parts')
INSERT INTO [dbo].[Materials] ([Description]) VALUES ('Efficient Mechanical Parts')
INSERT INTO [dbo].[Materials] ([Description]) VALUES ('Vindertech Mechanical Parts')
INSERT INTO [dbo].[Materials] ([Description]) VALUES ('Rough Mineral Powder')
INSERT INTO [dbo].[Materials] ([Description]) VALUES ('Simple Mineral Powder')
INSERT INTO [dbo].[Materials] ([Description]) VALUES ('Fine-grain Mineral Powder')
INSERT INTO [dbo].[Materials] ([Description]) VALUES ('Char-Black Mineral Powder')
INSERT INTO [dbo].[Materials] ([Description]) VALUES ('Oxidized Mineral Powder')
INSERT INTO [dbo].[Materials] ([Description]) VALUES ('Spectral Mineral Powder')
INSERT INTO [dbo].[Materials] ([Description]) VALUES ('Nuts n Bolts')
INSERT INTO [dbo].[Materials] ([Description]) VALUES ('Copper Ore')
INSERT INTO [dbo].[Materials] ([Description]) VALUES ('Silver Ore')
INSERT INTO [dbo].[Materials] ([Description]) VALUES ('Malachite Ore')
INSERT INTO [dbo].[Materials] ([Description]) VALUES ('Obsidian Ore')
INSERT INTO [dbo].[Materials] ([Description]) VALUES ('Brightcore Ore')
INSERT INTO [dbo].[Materials] ([Description]) VALUES ('Spectrolite Ore')
INSERT INTO [dbo].[Materials] ([Description]) VALUES ('Planks')
INSERT INTO [dbo].[Materials] ([Description]) VALUES ('Quartz Crystal')
INSERT INTO [dbo].[Materials] ([Description]) VALUES ('Rotating Gizmo')
INSERT INTO [dbo].[Materials] ([Description]) VALUES ('Rough Ore')
INSERT INTO [dbo].[Materials] ([Description]) VALUES ('Stringy Twine')
INSERT INTO [dbo].[Materials] ([Description]) VALUES ('Simple Twine')
INSERT INTO [dbo].[Materials] ([Description]) VALUES ('Sturdy Twine')
INSERT INTO [dbo].[Materials] ([Description]) VALUES ('Peaky Twine')
INSERT INTO [dbo].[Materials] ([Description]) VALUES ('Carved Twine')
INSERT INTO [dbo].[Materials] ([Description]) VALUES ('Spectral Twine')
