//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xolartek.Web.XoService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="XoService.IXolarService")]
    public interface IXolarService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IXolarService/GetSchematics", ReplyAction="http://tempuri.org/IXolarService/GetSchematicsResponse")]
        System.Collections.Generic.List<Xolartek.Entities.Schematic> GetSchematics();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IXolarService/GetSchematics", ReplyAction="http://tempuri.org/IXolarService/GetSchematicsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Xolartek.Entities.Schematic>> GetSchematicsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IXolarService/GetMaterials", ReplyAction="http://tempuri.org/IXolarService/GetMaterialsResponse")]
        System.Collections.Generic.List<Xolartek.Entities.Material> GetMaterials();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IXolarService/GetMaterials", ReplyAction="http://tempuri.org/IXolarService/GetMaterialsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Xolartek.Entities.Material>> GetMaterialsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IXolarService/GetTraits", ReplyAction="http://tempuri.org/IXolarService/GetTraitsResponse")]
        System.Collections.Generic.List<Xolartek.Entities.Trait> GetTraits();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IXolarService/GetTraits", ReplyAction="http://tempuri.org/IXolarService/GetTraitsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Xolartek.Entities.Trait>> GetTraitsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IXolarServiceChannel : Xolartek.Web.XoService.IXolarService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class XolarServiceClient : System.ServiceModel.ClientBase<Xolartek.Web.XoService.IXolarService>, Xolartek.Web.XoService.IXolarService {
        
        public XolarServiceClient() {
        }
        
        public XolarServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public XolarServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public XolarServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public XolarServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<Xolartek.Entities.Schematic> GetSchematics() {
            return base.Channel.GetSchematics();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Xolartek.Entities.Schematic>> GetSchematicsAsync() {
            return base.Channel.GetSchematicsAsync();
        }
        
        public System.Collections.Generic.List<Xolartek.Entities.Material> GetMaterials() {
            return base.Channel.GetMaterials();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Xolartek.Entities.Material>> GetMaterialsAsync() {
            return base.Channel.GetMaterialsAsync();
        }
        
        public System.Collections.Generic.List<Xolartek.Entities.Trait> GetTraits() {
            return base.Channel.GetTraits();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Xolartek.Entities.Trait>> GetTraitsAsync() {
            return base.Channel.GetTraitsAsync();
        }
    }
}
